default[:graylog2][:web_version] = '0.20.0-rc.2'
default[:graylog2][:web_home] = '/opt/graylog2-web-interface'
default[:graylog2][:web_user] = 'graylog2-web'
default[:graylog2][:web_service_name] = 'graylog2-web-interface'
default[:graylog2][:web_group] = 'graylog2'
default[:graylog2][:web_url] = 'http://localhost:9000/'
default[:graylog2][:web_context] = "/" # only root currently supported, see: https://github.com/Graylog2/graylog2-web-interface/issues/588
default[:graylog2][:web_mem] = 256
default[:graylog2][:web_tz] = 'Europe/Amsterdam'
default[:graylog2][:web_package] = "https://github.com/Graylog2/graylog2-web-interface/releases/download/#{node[:graylog2][:web_version]}/graylog2-web-interface-#{node[:graylog2][:web_version]}.tgz"
